{% set version = "0.5.12" %}
{% set name = "lap" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lap-{{ version }}.tar.gz
  sha256: 570b414ea7ae6c04bd49d0ec8cdac1dc5634737755784d44e37f9f668bab44fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  
requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.8.0
    - cython >=0.29.32
    - numpy >=1.21.6
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.6
test:
  imports:
    - lap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/gatagat/lap
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Linear Assignment Problem solver (LAPJV/LAPMOD)'
  dev_url: https://github.com/gatagat/lap

extra:
  recipe-maintainers:
    - primozgodec
